# Generated by Django 4.1.6 on 2023-04-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='img',
        ),
    ]
