# Generated by Django 4.1.6 on 2023-04-16 02:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_airport_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='image_url',
        ),
        migrations.AddField(
            model_name='airport',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
